### ISSUE TITLE
Average around multiple passes when performing the sorting

### ISSUE THREAD

**Issue by ulrichzoltan** [adrianvoica/CustomSortPerformance#2]
Each algorithm should be applied several times on different data sets and the result should be the average of those passes.

**Comment by adrianvoica** [comment]
ETA 1h

**Comment by adrianvoica** [comment]
Done.

**Comment by ulrichzoltan** [comment]
Code Review on e183ee01f923b2ab55310c46bfe200cef47625f6.
The initial estimate was 1h. Around 8h were spent since. What is the new estimate, taking into account the changes after the code review?

**Comment by adrianvoica** [comment]
ETA 4h

**Comment by ulrichzoltan** [comment]
Fixed by averaging 5 iterations per algorithm.
