### ISSUE TITLE
Have a way to keep a history of the tests performed

### ISSUE THREAD

**Issue by ulrichzoltan** [adrianvoica/CustomSortPerformance#3]
A history of the tests should be kept, allowing the user to inspect older tests and perform new ones. Use a UITableView to present the historical entries. Each entry (cell) should take the user to further details about the test.

**Comment by adrianvoica** [comment]
ETA 4h

**Comment by adrianvoica** [comment]
ETA 8h

**Comment by adrianvoica** [comment]
Done. Pending code review.

**Comment by ulrichzoltan** [comment]
How long did it actually take?

**Comment by adrianvoica** [comment]
Besides learning time, about 24 working hours (still, interleaved with some learning sessions).
