### ISSUE TITLE
The tests should not block the UI thread

### ISSUE THREAD

**Issue by ulrichzoltan** [adrianvoica/CustomSortPerformance#5]
When performing the tests, the UI is blocked. That should not happen.
The tests need to be performed on a different thread.

**Comment by adrianvoica** [comment]
ETA .5h

**Comment by adrianvoica** [comment]
Done.

**Comment by ulrichzoltan** [comment]
Still pending review changes on e183ee01f923b2ab55310c46bfe200cef47625f6

**Comment by adrianvoica** [comment]
ETA 1h

**Comment by ulrichzoltan** [comment]
Done by performing the tests on a global queue with default priority.
