### ISSUE TITLE
Incorrect display of results in history view

### ISSUE THREAD

**Issue by BalintDezso** [adrianvoica/CustomSortPerformance#8]
Steps to reproduce:
1. Delete all test results so you have nothing on the History view. 
2. Add two new tests of type integer (note the number of items selected during the test)
3. The first tests will display 1 less item than actually selected while the second test will be a clone of the first even tough different numbers were selected and it was preformed at a different time. 
4. Any further tests inserted into the History view will have incorrect item numbers and are inserted between the first two cloned tests. 

![ios simulator screen shot mar 10 2015 8 50 04 am](https://cloud.githubusercontent.com/assets/1953238/6570397/7af44a28-c702-11e4-9adf-b3a450a58ccd.png)

**Comment by adrianvoica** [comment]
Done. 4h.
